### ISSUE TITLE
Add an underscore to 6 and 9

### ISSUE THREAD

**Issue by agaertner** [QuitarHero/Heros-Marker-Pack#64]
These aren't distinguishable in 3D environment -> https://i.imgur.com/idEz58o.png
To fix, add an underscore to mark an imaginary bottom line to 6 and 9 much like how [Uno](https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Baraja_de_UNO.JPG/220px-Baraja_de_UNO.JPG) does it.

**Comment by QuitarHero** [comment]
While not directly addressed, a solution will be provided next release.
