### ISSUE TITLE
Numbers in Solid Ocean Fractal are imperceptible

### ISSUE THREAD

**Issue by jojorne** [QuitarHero/Heros-Marker-Pack#71]
You have placed numbers where the Jade Colossus will appear, but the numbers are the same color as the floor. Add just a bit transparency and they disappear completely.

**Comment by jojorne** [comment]
Take the number 7 as an example:
![image](https://user-images.githubusercontent.com/18329136/152628121-b7eefafb-eeac-4a93-a20a-b0d800b165b2.png)
![image](https://user-images.githubusercontent.com/18329136/152628128-97c44271-11e3-4ab6-af61-b571d1830c43.png)

**Comment by QuitarHero** [comment]
I've made a solution that while I'm not happy with it, will solve the issue you described, though the Solid Ocean arena may be _slightly_ more intrusive. Will be provided in the next release, which may be before EoD comes out.
